# Generated by Django 3.0.6 on 2020-05-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomaster',
            options={'verbose_name_plural': 'Todo Master Db'},
        ),
    ]
